[package]
name = "obiwan"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
log = "0.4.18"
anyhow = "1.0.71"
clap = { version = "4.3.1", features = [ "derive" ] }
stderrlog = "0.5.4"
nix = "0.26.2"
# TODO Strip this down.
tokio = { version = "1.28.2", features = ["full"] }
binrw = "0.11.2"
